DLS-8463: Updates Enter business details
hmrc/soft-drinks-industry-levy-registration-frontend pull request #72
Opened 2023-08-03 11:27 UTC by drewmiley

2023-08-03 11:27 UTC, drewmiley commented
<img width="614" alt="Screenshot 2023-08-03 at 11 53 54" src="https://github.com/hmrc/soft-drinks-industry-levy-registration-frontend/assets/13115186/91a26ed9-3a21-418a-a338-bcce4d35f8ec">

2023-08-07 11:15 UTC, ginnyamazed requested changes

2023-08-07 11:15 UTC, ginnyamazed commented on conf/messages.en
> +enterBusinessDetails.subtext2 = You will need to enter your Corporation Tax or company Unique Taxpayer Reference number (UTR). You can <a href={0} target="_blank">find a lost UTR (opens in new tab).<
This should be: 
You can <a class='govuk-link' href={0} target="_blank">find a lost UTR (opens in new tab).</a>

2023-08-07 11:15 UTC, ginnyamazed commented on conf/messages.en
> +enterBusinessDetails.subtext2 = You will need to enter your Corporation Tax or company Unique Taxpayer Reference number (UTR). You can <a href={0} target="_blank">find a lost UTR (opens in new tab).<
it isn't showing, sorry:  Please add class='govuk-link' to the <a href

2023-08-07 11:27 UTC, ginnyamazed approved these changes

2023-08-07 11:27 UTC, merged